export const EVENT_STORE_SETTINGS_TOKEN = 'EVENT_STORE_SETTINGS_TOKEN';
export const EVENT_STORE_TRANSFORMERS_TOKEN = 'EVENT_STORE_TRANSFORMERS_TOKEN';
export const AGGREGATE_ROOT_HANDLERS_KEY = 'AGGREGATE_ROOT_HANDLERS_KEY';
